### ISSUE TITLE
Unexpected exception during editing a file

### ISSUE THREAD

**Issue by mgr32** [mgr32/PsISEProjectExplorer#33]
An unhandled exception occurred in PsISEProjectExplorer: 
System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at PsISEProjectExplorer.UI.ViewModel.TreeViewModel.<>c__DisplayClass9.<RefreshFromIntermediateNode>b__5(TreeViewEntryItemModel treeViewChild)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at PsISEProjectExplorer.UI.ViewModel.TreeViewModel.RefreshFromIntermediateNode(INode node, TreeViewEntryItemModel treeViewEntryItem, Boolean expandAllNodes)
   at PsISEProjectExplorer.UI.ViewModel.MainViewModel.<>c__DisplayClass10.<OnSearchingFinished>b__d()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at PsISEProjectExplorer.UI.ViewModel.MainViewModel.OnSearchingFinished(Object sender, SearcherResult result)
   at PsISEProjectExplorer.UI.ViewModel.IndexingSearchingModel.BackgroundSearcherWorkCompleted(Object sender, RunWorkerCompletedEventArgs e)
   at PsISEProjectExplorer.UI.ViewModel.IndexingSearchingModel.RunSearch(BackgroundSearcherParams searcherParams)
   at PsISEProjectExplorer.UI.ViewModel.MainViewModel.RunSearch(String path)
   at PsISEProjectExplorer.Services.DocumentHierarchyFactory.<GetFileList>d__4.MoveNext()
   at PsISEProjectExplorer.Services.DocumentHierarchyFactory.UpdateDocumentHierarchy(IEnumerable`1 pathsToUpdate, FilesPatternProvider filesPatternProvider, BackgroundIndexer worker)
   at PsISEProjectExplorer.UI.Workers.BackgroundIndexer.RunIndexing(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at PsISEProjectExplorer.UI.ViewModel.IndexingSearchingModel.BackgroundIndexerWorkCompleted(Object sender, RunWorkerCompletedEventArgs e)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by mgr32** [comment]
An unhandled exception occurred in PsISEProjectExplorer: 
System.ArgumentOutOfRangeException: Insertion index was out of range. Must be non-negative and less than or equal to size.
Parameter name: index
   at System.Collections.ArrayList.Insert(Int32 index, Object value)
   at System.Windows.Data.ListCollectionView.AdjustShadowCopy(NotifyCollectionChangedEventArgs e)
   at System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   at System.Windows.Data.CollectionView.ProcessChangeLog(ArrayList changeLog, Boolean processAll)
   at System.Windows.Data.CollectionView.ProcessInvoke(Object arg)
   at MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by mgr32** [comment]
First one should be fixed in v1.2.3.
Second one is probably due to http://blog.quantumbitdesigns.com/2008/07/22/wpf-cross-thread-collection-binding-part-1/ and needs fixing.

**Comment by mgr32** [comment]
ERROR|PsISEProjectExplorer.ProjectExplorerWindow.DispatcherUnhandledExceptionHandler|Unhandled Dispatcher exception System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at PsISEProjectExplorer.UI.ViewModel.TreeViewModel.DeleteTreeViewEntryItemModel(TreeViewEntryItemModel item, Boolean first)
   at PsISEProjectExplorer.UI.ViewModel.TreeViewModel.RefreshFromIntermediateNode(INode node, TreeViewEntryItemModel treeViewEntryItem, Boolean expandAllNodes)
   at PsISEProjectExplorer.UI.ViewModel.MainViewModel.<>c__DisplayClass10.<OnSearchingFinished>b__d()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at PsISEProjectExplorer.UI.ViewModel.MainViewModel.OnSearchingFinished(Object sender, SearcherResult result)
   at PsISEProjectExplorer.UI.ViewModel.IndexingSearchingModel.BackgroundSearcherWorkCompleted(Object sender, RunWorkerCompletedEventArgs e)
   at PsISEProjectExplorer.UI.ViewModel.IndexingSearchingModel.RunSearch(BackgroundSearcherParams searcherParams)
   at PsISEProjectExplorer.UI.ViewModel.MainViewModel.RunSearch(String path)
   at PsISEProjectExplorer.Services.DocumentHierarchyFactory.<GetFileList>d__4.MoveNext()
   at PsISEProjectExplorer.Services.DocumentHierarchyFactory.UpdateDocumentHierarchy(IEnumerable`1 pathsToUpdate, FilesPatternProvider filesPatternProvider, BackgroundIndexer worker)
   at PsISEProjectExplorer.UI.Workers.BackgroundIndexer.RunIndexing(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at PsISEProjectExplorer.UI.ViewModel.IndexingSearchingModel.BackgroundIndexerWorkCompleted(Object sender, RunWorkerCompletedEventArgs e)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
