### ISSUE TITLE
An unhandled exception: System.NullReferenceException

### ISSUE THREAD

**Issue by kRaVeda** [mgr32/PsISEProjectExplorer#42]
An unhandled exception occurred in PsISEProjectExplorer: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.DependencyObject.LookupEntry(Int32 targetIndex)
   at System.Windows.DependencyObject.ClearValue(DependencyPropertyKey key)
   at System.Windows.ReverseInheritProperty.FirePropertyChangeInAncestry(DependencyObject element, Boolean oldValue, DeferredElementTreeState treeState, Action`2 originChangedAction)
   at System.Windows.ReverseInheritProperty.FirePropertyChangeInAncestry(DependencyObject element, Boolean oldValue, DeferredElementTreeState treeState, Action`2 originChangedAction)
   at System.Windows.ReverseInheritProperty.FirePropertyChangeInAncestry(DependencyObject element, Boolean oldValue, DeferredElementTreeState treeState, Action`2 originChangedAction)
   at System.Windows.ReverseInheritProperty.OnOriginValueChanged(DependencyObject oldOrigin, DependencyObject newOrigin, IList`1 otherOrigins, DeferredElementTreeState& oldTreeState, Action`2 originChangedAction)
   at System.Windows.ReverseInheritProperty.OnOriginValueChanged(DependencyObject oldOrigin, DependencyObject newOrigin, DeferredElementTreeState& oldTreeState)
   at System.Windows.Input.MouseDevice.ChangeMouseOver(IInputElement mouseOver, Int32 timestamp)
   at System.Windows.Input.MouseDevice.PreNotifyInput(Object sender, NotifyInputEventArgs e)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.MouseDevice.Synchronize()
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.OnGotKeyboardFocus(Object sender, KeyboardFocusChangedEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.KeyboardDevice.ChangeFocus(DependencyObject focus, Int32 timestamp)
   at System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
   at System.Windows.UIElement.Focus()
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextViewHost.<InitializeComponent>b__0(Object param0)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by mgr32** [comment]
Thank you, I believe this actually does not come from PsISEProjectExplorer - ver <= 1.2.2 caught all unhandled exceptions, and due to issue #37 it erroneously said it's from PsISEProjectExplorer. You could download new version (v1.2.3) to have better logging and to leave ISE working. 
I could say more if you're able to write the steps to recreate the issue, or recreate it yourself and attach the log file from the new version here.

**Comment by kRaVeda** [comment]
Thank you. I have installed v1.2.3, and if this version crashed, I'll send
you log.

**Comment by mgr32** [comment]
Closing due to no activity - feel free to reopen if the issue still occurs.
